### ISSUE TITLE
JsonAwareResponse::getBody() must be compatible with GuzzleHttp\Psr7\Response::getBody()

### ISSUE THREAD

**Issue by midsonlajeanty** [Fruitsbytes/php-moncash#1]
Declaration of Fruitsbytes\PHP\Moncash\JsonAwareResponse::getBody() must be compatible with GuzzleHttp\Psr7\Response::getBody(): Psr\Http\Message\StreamInterface

**Comment by bleuscyther** [comment]
Planning a working Release on this [branch](https://github.com/Fruitsbytes/php-moncash/tree/feature/unit-tests-upgrades-and-refactoring).
Should be available this week
